/**
 * M5 UI shell. Deliberately thin: it builds a generation request and renders the result.
 * No planning logic lives here — the engine is the only thing that decides what to train
 * (ADR-002). If a rule appears in this file, it is in the wrong place.
 *
 * Planner state persists to IndexedDB via ../storage/. This file decides WHEN
 * to save (debounced off paint, flushed on visibilitychange) and never HOW:
 * canonical form, versioning and the export envelope live in state.js so they
 * stay testable in node --test (#35, ADR-011).
 *
 * ADR-027: blocks now hold an ordered list of setGroups. Two consequences visible
 * throughout this file:
 *
 *   - Addressing gains one index. Every edit control carries (w, s, b, g) instead
 *     of (w, s, b), and resolves through `setGroupAt` rather than reaching into
 *     the shape. A superset's second exercise is reachable without this file
 *     knowing what a superset is.
 *
 *   - The load/time branch is gone from the block level. `intervalDomain` no
 *     longer emits `stations[]`, so one renderer walks `session.blocks` for both
 *     domains and switches on `blockType` for the group-level chrome. The domain
 *     branch that remains is only about session-level framing — rounds and a
 *     time cap versus a fatigue total.
 */
import { generate, CoverageError } from '../engine/index.js';
import { rankSubstitutes } from '../engine/substitution.js';
import { allSetGroups, setGroupAt } from '../engine/blocks.js';
import * as db from '../storage/db.js';
import {
  emptyState, putPlan, toExportJSON, fromImportJSON, toCSV, replaceImportedSets,
  appendExerciseMax, currentMax, putProfile, removeProfile,
  replaceImportedDayNotes, notesForDate, putSessionNote
} from '../storage/state.js';
import { toFitNotesCSV, planDates } from '../storage/fitnotes-export.js';
import { SqliteFile } from '../storage/sqlite.js';
import { importFitNotes } from '../storage/fitnotes.js';
// Generated by tools/build_fitnotes_manifest.py from the authored CSV. Bundled
// and precached like any definition file, so import works offline (ADR-001).
// Imported HERE rather than in engine/defs.js: ADR-031 keeps FitNotes identity
// out of the engine, and this file is the edge.
import mappingFile from '../data/fitnotes-mapping.json' with { type: 'json' };

const PREF_PROFILE = 'pref:equipmentProfile';
const DEFAULT_PROFILE = 'home-garage';

/** The program currently on screen. Mutated by edits, then persisted by paint(). */
let current = null;
let currentDefs = null;
let currentRequest = null;
let visibleDay = 0;        // single-session mode: which day of the split is shown
let scope = 'session';     // 'session' | 'block'
let edited = false;
let pinnedSeed = null;     // set when the user asks to reproduce a draft
let seedLabel = '';         // the user's number/name, shown separately from the resolved integer

/**
 * ONE stored draft, not a plan library. `plans` is an array and `putPlan` keys on
 * id, so many are storable - but this UI has no plan list, no picker and no
 * delete, so persisting every Generate click would accumulate drafts the athlete
 * can neither see nor remove. Data with no surface is worse than no data.
 */
const DRAFT_ID = 'draft:current';

/** Canonical state as last loaded or saved. Null until hydrate() resolves. */
let persisted = null;
/** True while restoring, so hydrating a draft does not immediately re-save it. */
let hydrating = false;
let saveTimer = null;
/** What the sidebar says about persistence. Empty means nothing worth saying. */
let storageNote = '';

/** The SHIPPED profiles, captured before any merge. Merging into a merged
 * list would let an authored profile become part of the baseline it is added to. */
let shippedProfiles = [];

/**
 * Session index -> moved date, for THIS export only (#54).
 *
 * Deliberately not persisted. A stored date override is authored state, which
 * means a STATE_VERSION bump, a migration, and the imported-versus-authored
 * question #50 has not settled yet. The output is a file downloaded once; if
 * these should outlive the tab, that is its own issue with its own migration.
 */
let dateOverrides = {};

/**
 * Exercises the last import could not resolve, kept on screen until they are
 * mapped. NOT a flash message: ADR-023 computes e1RM from `exerciseId`, so an
 * unresolved row contributes nothing to progression while still occupying
 * history. A count that vanishes is not a review mechanism (#24).
 */
let importReview = [];
let reviewEl = null;
let maxListEl = null;

/** fitnotesId -> mapping row. Keyed on the NUMERIC id: FitNotes lets the
 *  athlete rename any row, and a name-keyed join is how a renamed row lands
 *  its history on a different lift (#33). */
const MAPPING = new Map(mappingFile.exercises.map((e) => [e.fitnotesId, e]));
let statusEl = null;

/** Numeric seeds pass through; named seeds hash deterministically to a positive integer. */
function seedFrom(raw) {
  const value = String(raw ?? '').trim();
  seedLabel = value;
  if (!value) return nextSeed();

  const n = Number(value);
  if (Number.isInteger(n) && n > 0) return n;

  // FNV-1a keeps memorable labels such as "Mine" reproducible while the engine
  // continues receiving the integer seed required by its request contract.
  let hash = 2166136261;
  for (const char of value) {
    hash ^= char.codePointAt(0);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0) || 1;
}

function nextSeed() {
  if (pinnedSeed !== null) { const s = pinnedSeed; pinnedSeed = null; return s; }
  return Math.floor(Math.random() * 2_000_000_000);
}

export function mount(root, defs) {
  currentDefs = defs;
  root.setAttribute('aria-busy', 'false');

  const savedProfile = localStorage.getItem(PREF_PROFILE);
  const profileExists = (id) => defs.equipment.some((p) => p.id === id);
  const selectedProfile =
    (savedProfile && profileExists(savedProfile) && savedProfile) ||
    (profileExists(DEFAULT_PROFILE) && DEFAULT_PROFILE) ||
    defs.equipment[0]?.id;

  root.innerHTML = `
    <header class="app-bar">
      <h1>Training Planner</h1>
      <div class="app-actions">
        ${import.meta.env.DEV ? `
          <label class="preview-control">Preview
            <select id="preview" aria-label="Responsive preview">
              <option value="auto">Auto</option>
              <option value="phone">Phone · 390px</option>
              <option value="desktop">Desktop</option>
            </select>
          </label>` : ''}
        <button id="theme" class="ghost icon-button" aria-label="Toggle theme">◐</button>
      </div>
    </header>

    <aside class="planner-sidebar">
      <form id="req" class="panel planner-form">
      <label>View
        <select name="scope">
          <option value="session" selected>One day at a time</option>
          <option value="block">All weeks</option>
        </select>
      </label>
      <label>Style
        <select name="styleId">
          ${defs.styles.map((s) => `<option value="${s.id}">${esc(s.name)} — ${s.domain === 'load' ? 'load' : 'time'}</option>`).join('')}
        </select>
      </label>
      <label>Equipment
        <select name="equipmentProfile">
          ${defs.equipment.map((p) => `
            <option value="${p.id}"${p.id === selectedProfile ? ' selected' : ''}>${esc(p.name)}</option>
          `).join('')}
        </select>
      </label>
      <fieldset class="weekdays">
        <legend>Days I can train</legend>
        <!-- AVAILABILITY, not frequency. These are the days training is
             POSSIBLE; sessionsPerWeek below is how many the athlete wants. The
             engine picks the best-spaced subset (#25), which is coach work the
             athlete should not have to do by hand. -->
        <label><input type="checkbox" name="availableDay" value="mon" checked /><span>Mon</span></label>
        <label><input type="checkbox" name="availableDay" value="tue" checked /><span>Tue</span></label>
        <label><input type="checkbox" name="availableDay" value="wed" checked /><span>Wed</span></label>
        <label><input type="checkbox" name="availableDay" value="thu" checked /><span>Thu</span></label>
        <label><input type="checkbox" name="availableDay" value="fri" checked /><span>Fri</span></label>
        <label><input type="checkbox" name="availableDay" value="sat" checked /><span>Sat</span></label>
        <label><input type="checkbox" name="availableDay" value="sun" checked /><span>Sun</span></label>
      </fieldset>
      <label>Sessions / week
        <input type="number" name="daysPerWeek" min="1" max="7" value="4" />
      </label>
      <label class="block-only">Block length (weeks)
        <input type="number" name="blockWeeks" min="1" max="12" value="4" />
      </label>
      <label>Skill level (1–5)
        <input type="number" name="skillLevel" min="1" max="5" value="2" />
      </label>
      <label>Seed (number or name; blank = new draft)
        <input type="text" name="seed" placeholder="random"
               autocomplete="off" />
      </label>
        <button type="submit" class="primary">Generate</button>
      </form>

      <div class="storage-panel">
        <div class="storage-actions">
          <button type="button" id="export" class="ghost">Export backup</button>
          <button type="button" id="import" class="ghost">Import backup</button>
          <button type="button" id="export-csv" class="ghost">Export history CSV</button>
          <button type="button" id="import-fitnotes" class="ghost">Import FitNotes history</button>
          <label class="export-start">Block starts
            <input type="date" id="export-start" />
          </label>
          <button type="button" id="export-plan" class="ghost">Export plan to FitNotes</button>
          <div id="date-preview" class="date-preview"></div>
          <input type="file" id="import-file" accept="application/json,.json" hidden />
          <input type="file" id="fitnotes-file" accept=".fitnotes,.db,.sqlite" hidden />
        </div>
        <p id="storage-status" class="note" role="status"></p>
        <div id="import-review"></div>
      </div>

      <div class="profile-panel">
        <h3>Equipment profile</h3>
        <div id="profile-editor"></div>
      </div>

      <div class="maxes-panel">
        <h3>Known maxes</h3>
        <p class="note">
          A percentage prescription needs a max to multiply against. Your newest
          logged session is 516 days old, well past ADR-023's 8-week resolution
          window, so entering a max is the only thing that yields a real weight
          today -- and a tested max stays better than an inferred one afterwards.
        </p>
        <label>Lift
          <select id="max-exercise"></select>
        </label>
        <label>One-rep max (lb)
          <input type="number" id="max-value" min="1" max="1200" step="0.5"
                 placeholder="225" />
        </label>
        <button type="button" id="max-save" class="ghost">Save max</button>
        <div id="max-list"></div>
      </div>
    </aside>
    <section id="out" aria-live="polite"></section>
  `;

  const form = root.querySelector('#req');
  const out = root.querySelector('#out');

  // Days/week still matters in single-session mode: it picks the split, and a
  // 3-day split's "Full Body A" is not a 6-day split's "Push A". Block length
  // does not, so it is hidden rather than left present and ignored.
  const syncScope = () => {
    scope = form.scope.value;
    form.querySelector('.block-only').hidden = scope === 'session';
  };
  // Sessions cannot exceed availability. The engine rejects that correctly, but
  // discovering it after pressing Generate is a worse way to learn it.
  for (const box of form.querySelectorAll('[name=availableDay]')) {
    box.addEventListener('change', () => clampSessions(form));
  }
  clampSessions(form);

  form.scope.addEventListener('change', syncScope);
  syncScope();

  form.equipmentProfile.addEventListener('change', (e) => {
    localStorage.setItem(PREF_PROFILE, e.target.value);
    paintProfiles();
  });

  const preview = root.querySelector('#preview');
  if (preview) {
    preview.addEventListener('change', () => {
      document.documentElement.dataset.preview = preview.value;
    });
    document.documentElement.dataset.preview = preview.value;
  }

  root.querySelector('#theme').addEventListener('click', () => {
    const el = document.documentElement;
    el.dataset.theme = el.dataset.theme === 'dark' ? 'light' : 'dark';
    localStorage.setItem('theme', el.dataset.theme);
  });
  document.documentElement.dataset.theme = localStorage.getItem('theme') ?? 'dark';

  statusEl = root.querySelector('#storage-status');
  reviewEl = root.querySelector('#import-review');

  // Defaults to today, LOCAL. en-CA formats as YYYY-MM-DD, which is what
  // fitnotes-export.js validates; toISOString() is UTC and can be a day off.
  const startEl = root.querySelector('#export-start');
  startEl.value = new Date().toLocaleDateString('en-CA');
  startEl.addEventListener('change', () => { dateOverrides = {}; paintDates(); });

  shippedProfiles = defs.equipment;
  // Set at MOUNT, not only on generate. paintProfiles() bails when currentDefs
  // is null, so the editor rendered nothing until the first plan was generated
  // -- an empty panel under a heading, which reads as a broken build (#8).
  currentDefs = currentDefs ?? defs;

  root.querySelector('#profile-editor').addEventListener('click', async (e) => {
    const save = e.target.closest('#profile-save');
    const del = e.target.closest('#profile-delete');
    if (!save && !del) return;

    const panel = root.querySelector('#profile-editor');
    const base = persisted ?? emptyState();

    if (del) {
      const id = root.querySelector('[name=equipmentProfile]').value;
      if (!window.confirm('Delete this profile? Plans already generated are unaffected.')) return;
      const { ok, error } = await db.trySave(removeProfile(base, id));
      storageNote = ok ? 'Profile deleted.' : `Not deleted: ${error?.message ?? 'unknown'}`;
      if (ok) persisted = removeProfile(base, id);
      paintStatus();
      paintProfiles();
      return;
    }

    const name = panel.querySelector('#profile-name').value.trim();
    if (!name) { storageNote = 'Name the profile before saving it.'; paintStatus(); return; }

    const available = [...panel.querySelectorAll('[name=token]:checked')].map((b) => b.value);
    const profile = {
      id: profileId(name), name, available, editable: true, userDefined: true
    };

    try {
      // Shipped ids are passed so state.js can refuse a shadow rather than
      // leaving resolution to depend on merge order.
      const next = putProfile(base, profile, shippedProfiles.map((x) => x.id));
      const { ok, error } = await db.trySave(next);
      if (!ok) { storageNote = `Profile not saved: ${error?.message ?? 'unknown'}`; paintStatus(); return; }
      persisted = next;
      storageNote = `Saved "${name}" with ${available.length} items.`;
      paintProfiles();
      root.querySelector('[name=equipmentProfile]').value = profile.id;
      paintProfiles();
    } catch (err) {
      storageNote = `Profile refused: ${err.message}`;
    }
    paintStatus();
  });

  root.querySelector('#date-preview').addEventListener('change', async (e) => {
    const noteEl = e.target.closest('[data-note-date]');
    if (noteEl) {
      const next = putSessionNote(persisted ?? emptyState(), noteEl.dataset.noteDate, noteEl.value);
      const { ok, error } = await db.trySave(next);
      if (ok) persisted = next;
      else storageNote = `Note not saved: ${error?.message ?? 'unknown'}`;
      paintStatus();
      return;
    }

    const input = e.target.closest('[data-date-index]');
    if (!input) return;
    const i = Number(input.dataset.dateIndex);
    const rows = planDates(current, startEl.value, (persisted ?? emptyState()).importedSets);
    if (input.value === rows[i].date) delete dateOverrides[i];
    else dateOverrides[i] = input.value;
    paintDates();
  });

  root.querySelector('#export-plan').addEventListener('click', () => {
    if (!current) {
      storageNote = 'Generate a plan before exporting it.';
      paintStatus();
      return;
    }
    try {
      const state = persisted ?? emptyState();
      // Export exactly the dates on screen. Recomputing them here would mean
      // the athlete reviewed one list and exported another.
      const planned = planDates(current, startEl.value, state.importedSets, dateOverrides);
      const broken = planned.filter((r) => r.outOfOrder);
      if (broken.length) {
        storageNote = `Session ${broken[0].index + 1} (${broken[0].label}) is dated on or `
          + 'before the session before it. Session order is training order, so this cannot '
          + 'be exported. Move it later, or reset it to its computed date.';
        paintStatus();
        return;
      }

      const out = toFitNotesCSV(current, startEl.value, state, {
        manifest: mappingFile,
        catalog: currentDefs.exercises,
        currentMax,
        dates: planned.map((r) => r.date)
      });

      // The collision confirm that used to sit here is gone (#54). Clashes are
      // marked in the date preview above the button, before the click — the same
      // fact stated once, readably, instead of twice with one of them blocking.

      const url = URL.createObjectURL(new Blob([out.csv], { type: 'text/csv' }));
      const a = document.createElement('a');
      a.href = url;
      a.download = 'trainer-plan-' + startEl.value + '.csv';
      a.click();
      URL.revokeObjectURL(url);

      // `unpriced` names lifts that NEED a max and lack one, so the athlete
      // learns which rows exported as a percentage rather than a weight.
      storageNote = out.rows + ' rows exported, ' + out.dates.length + ' sessions from '
        + out.dates[0] + ' to ' + out.dates[out.dates.length - 1] + '.'
        + (out.unpriced.length
          ? ' No max for: ' + out.unpriced.join(', ') + ' - exported as a percentage.'
          : '');
    } catch (err) {
      storageNote = 'Export failed: ' + err.message;
    }
    paintStatus();
  });
  maxListEl = root.querySelector('#max-list');

  // Lifts a percentage prescription can anchor to, derived from the catalog so
  // a catalog change cannot leave this list stale.
  //
  // ADR-023's rule is compound + weight_reps + fatigueCost >= 3 + barbell or
  // trap_bar. is_compound is NOT on the seed record -- build_seed.py drops the
  // column -- so a filter on it silently passes everything. Excluding carry by
  // hand stands in for it: it removes Trap Bar Farmer's Carry and Zercher
  // Carry, which have no meaningful one-rep max. Filed separately.
  const maxSelect = root.querySelector('#max-exercise');
  const anchored = defs.exercises
    .filter((e) =>
      e.scoring !== 'time' &&
      e.pattern !== 'carry' &&
      (e.fatigueCost ?? 0) >= 3 &&
      (e.equipment ?? []).some((t) => t === 'barbell' || t === 'trap_bar'))
    .sort((a, b) => (a.name < b.name ? -1 : 1));

  for (const exercise of anchored) {
    const option = document.createElement('option');
    option.value = exercise.id;
    option.textContent = exercise.name;
    maxSelect.appendChild(option);
  }

  root.querySelector('#max-save').addEventListener('click', async () => {
    const input = root.querySelector('#max-value');
    const value = Number(input.value);

    if (!(value > 0 && Number.isFinite(value))) {
      storageNote = 'Enter a weight in pounds.';
      paintStatus();
      return;
    }

    // APPEND-ONLY (ADR-023). A correction supersedes rather than overwrites, so
    // the history of estimates survives a replacement import. The store grows
    // with each edit and there is deliberately no delete.
    //
    // en-CA formats as YYYY-MM-DD in LOCAL time, which is what the store
    // validates. toISOString() would be UTC and can land a day off.
    const today = new Date().toLocaleDateString('en-CA');

    try {
      const next = appendExerciseMax(persisted ?? emptyState(), {
        id: 'max:' + maxSelect.value + ':' + today + ':' + Date.now(),
        exerciseId: maxSelect.value,
        e1rm: value,
        source: 'entered',
        effectiveDate: today
      });

      const saved = await db.trySave(next);
      if (!saved.ok) {
        storageNote = 'Max not stored: ' + (saved.error?.message ?? 'unknown');
        paintStatus();
        return;
      }

      persisted = next;
      input.value = '';
      storageNote = 'Saved ' + value + ' lb.';
    } catch (err) {
      storageNote = 'Max refused: ' + err.message;
    }
    paintStatus();
  });
  const importFile = root.querySelector('#import-file');

  root.querySelector('#export').addEventListener('click', () => {
    // Exports whatever is STORED, not what is on screen: the file has to be the
    // thing a wipe-and-import reproduces (ADR-011). A pending debounce would
    // otherwise export one edit behind.
    flushSave().then(() => {
      try {
        const json = toExportJSON(persisted ?? emptyState(), new Date().toISOString());
        const url = URL.createObjectURL(new Blob([json], { type: 'application/json' }));
        const a = document.createElement('a');
        a.href = url;
        a.download = `training-planner-${new Date().toISOString().slice(0, 10)}.json`;
        a.click();
        URL.revokeObjectURL(url);
        storageNote = 'Backup exported.';
      } catch (err) {
        storageNote = `Export failed: ${err.message}`;
      }
      paintStatus();
    });
  });

  // Generic CSV, for spreadsheets and other tools (#26). Not a backup: it holds
  // imported history only, and importing it back is not supported. The backup is
  // the JSON envelope above.
  root.querySelector('#export-csv').addEventListener('click', () => {
    flushSave().then(() => {
      const state = persisted ?? emptyState();
      if (!state.importedSets.length) {
        storageNote = 'No imported history to export yet.';
        paintStatus();
        return;
      }
      try {
        const url = URL.createObjectURL(new Blob([toCSV(state)], { type: 'text/csv' }));
        const a = document.createElement('a');
        a.href = url;
        a.download = `training-history-${new Date().toISOString().slice(0, 10)}.csv`;
        a.click();
        URL.revokeObjectURL(url);
        storageNote = `Exported ${state.importedSets.length} sets to CSV.`;
      } catch (err) {
        storageNote = `CSV export failed: ${err.message}`;
      }
      paintStatus();
    });
  });

  const fitnotesFile = root.querySelector('#fitnotes-file');
  root.querySelector('#import-fitnotes').addEventListener('click', () => fitnotesFile.click());

  fitnotesFile.addEventListener('change', async () => {
    const file = fitnotesFile.files?.[0];
    fitnotesFile.value = '';          // so re-picking the same file fires change
    if (!file) return;

    storageNote = 'Reading export…';
    paintStatus();

    // Parsed in memory and discarded. The raw database is never written to
    // IndexedDB and never transmitted (ADR-031 ruling 3, and #24's own criterion
    // that no source database is retained as a raw file).
    let result;
    try {
      const bytes = new Uint8Array(await file.arrayBuffer());
      result = importFitNotes(new SqliteFile(bytes), MAPPING);
    } catch (err) {
      // Fails closed. A file that is not a FitNotes export, a truncated copy off
      // a phone, or a weight that reverses to neither a pound nor a kilogram
      // step all land here and change nothing.
      storageNote = `Import refused: ${err.message} Nothing was changed.`;
      paintStatus();
      return;
    }

    // THE DRY RUN (#24). Replacement is destructive by design, so the numbers
    // are shown while the decision is still reversible.
    const s = result.summary;
    const proceed = window.confirm([
      `${file.name}`,
      '',
      `${s.logRows} rows in the export.`,
      `${s.skippedIncomplete} incomplete — templates and abandoned entries, not imported.`,
      `${s.imported} completed sets will be imported.`,
      `    ${s.resolved} matched to catalog exercises.`,
      `    ${s.unresolved} unmatched — kept and reviewable, but they do not feed progression.`,
      ...(s.dayNotes ? [`${s.dayNotes} day ${s.dayNotes === 1 ? 'note' : 'notes'} carried across.`] : []),
      '',
      'This REPLACES all previously imported history.',
      'Plans, settings, estimated maxes and your own session notes are untouched.',
      '',
      'Continue?'
    ].join('\n'));

    if (!proceed) {
      storageNote = 'Import cancelled. Nothing was changed.';
      paintStatus();
      return;
    }

    // WRAPPED because db.trySave deliberately RETHROWS StateError -- "our bug,
    // not the browser's". Without this the status line sticks on "Reading
    // export..." forever: the rejection escapes as an unhandled promise and
    // nothing repaints. That is exactly what happened on the first real import,
    // when one row carried an illegal distanceUnit. A failed import must SAY so.
    try {
      // Sets and day notes in ONE state object, so ONE trySave writes both.
      // Two saves could land sets without notes, leaving the two halves of a
      // single import disagreeing with no way to tell (#50).
      const next = replaceImportedDayNotes(
        replaceImportedSets(
          persisted ?? emptyState(), result.sets, new Date().toISOString()
        ),
        result.dayNotes
      );

      const { ok, error } = await db.trySave(next);
      if (!ok) {
        storageNote = `Import read correctly but could not be stored: ${error?.message ?? 'unknown'}`;
        paintStatus();
        return;
      }

      persisted = next;
      importReview = result.review;
      storageNote = `Imported ${s.imported} sets, ${s.resolved} matched`
        + (s.dayNotes ? `, ${s.dayNotes} day ${s.dayNotes === 1 ? 'note' : 'notes'}.` : '.');
    } catch (err) {
      // A row the validator refuses lands here. Nothing was written: trySave
      // validates before it opens a transaction.
      storageNote = `Import refused by validation: ${err.message} Nothing was stored.`;
    }
    paintStatus();
  });

  root.querySelector('#import').addEventListener('click', () => importFile.click());

  importFile.addEventListener('change', async () => {
    const file = importFile.files?.[0];
    importFile.value = '';          // so re-picking the same file fires change
    if (!file) return;
    if (!window.confirm(
      'Importing replaces everything this app has stored. Export first if you want to keep it. Continue?'
    )) return;

    let next;
    try {
      next = fromImportJSON(await file.text());
    } catch (err) {
      // Fails closed (#35): a refused import changes nothing at all.
      storageNote = `Import refused: ${err.message} Nothing was changed.`;
      paintStatus();
      return;
    }

    const { ok, error } = await db.trySave(next);
    if (!ok) {
      storageNote = `Import read correctly but could not be stored: ${error?.message ?? 'unknown'}`;
      paintStatus();
      return;
    }
    persisted = next;
    storageNote = 'Import complete.';
    restoreDraft(out, form);
  // After hydration: stored profiles exist now, so the picker and editor can
  // show them and currentDefs can carry them.
  paintProfiles();
  });

  // A phone switching apps is exactly when a pending debounce dies, and ADR-004
  // is explicit that there is no server to fall back on.
  document.addEventListener('visibilitychange', () => {
    if (document.visibilityState === 'hidden') flushSave();
  });

  // Render the editor BEFORE hydrate, and independently of it. Every other
  // paintProfiles() call sits downstream of a hydrate() branch, so any storage
  // failure left the panel blank under its heading -- which reads as a broken
  // build rather than as a storage problem. The editor needs no stored data:
  // the token list comes from the catalog.
  paintProfiles();
  hydrate(out, form);

  form.addEventListener('submit', (e) => {
    e.preventDefault();
    const f = new FormData(e.target);

    currentRequest = {
      schemaVersion: 1,
      styleId: f.get('styleId'),
      daysPerWeek: Number(f.get('daysPerWeek')),
      // The days training is possible. The engine chooses the best-spaced
      // subset of these; it never trains on a day not listed here.
      availableDays: f.getAll('availableDay'),
      // Single-session mode still generates a real week — see the note above.
      blockWeeks: scope === 'session' ? 1 : Number(f.get('blockWeeks')),
      equipmentProfile: f.get('equipmentProfile'),
      sessionMinutes: 70,
      // A new seed per click, so Generate means "give me a different draft"
      // rather than redrawing the same one. The engine stays deterministic
      // (ADR-002): the same seed always yields the same program, and the seed
      // is shown so a draft you liked can be reproduced.
      // An explicit seed reproduces a draft exactly (ADR-002). Blank means
      // "give me a different one", which is what Generate should mean by default.
      seed: seedFrom(f.get('seed')),
      athlete: { skillLevel: Number(f.get('skillLevel')), hasCoaching: false, strictReps: {} },
      history: []
    };

    visibleDay = 0;
    edited = false;

    try {
      current = generate(currentRequest, currentDefs);
      paint(out);
      dateOverrides = {};
      paintDates();
    } catch (err) {
      current = null;
      out.innerHTML = err instanceof CoverageError
        ? coverageHtml(err, currentDefs, currentRequest)
        : genericErrorHtml(err);
    }
  });

  // One delegated listener for every edit control. SetGroups are addressed by
  // (week, session, block, setGroup) index rather than by DOM position, so a
  // re-render cannot desynchronise the handler from the data.
  out.addEventListener('click', (e) => {
    const day = e.target.closest('[data-day]');
    if (day) {
      visibleDay = Number(day.dataset.day);
      paint(out);
      return;
    }

    const seed = e.target.closest('[data-copy-seed]');
    if (seed) {
      const value = seed.dataset.copySeed;
      navigator.clipboard?.writeText(value).catch(() => {});
      seed.textContent = 'copied';
      setTimeout(() => { if (seed.isConnected) seed.textContent = value; }, 900);
      return;
    }

    const swap = e.target.closest('[data-swap]');
    if (swap) {
      const { w, s, b, g } = indices(swap);
      toggleSwapList(out, swap, w, s, b, g);
      return;
    }

    const pick = e.target.closest('[data-pick]');
    if (pick) {
      const { w, s, b, g } = indices(pick);
      replaceSetGroup(w, s, b, g, pick.dataset.pick);
      edited = true;
      paint(out);
      return;
    }

    const remove = e.target.closest('[data-remove]');
    if (remove) {
      if (!window.confirm('Remove this exercise from the draft?')) return;
      const { w, s, b, g } = indices(remove);
      const block = current.weeks[w].sessions[s].blocks[b];
      block.setGroups.splice(g, 1);
      if (block.setGroups.length === 0) current.weeks[w].sessions[s].blocks.splice(b, 1);
      edited = true;
      paint(out);
    }
  });

  out.addEventListener('change', (e) => {
    const input = e.target.closest('[data-edit]');
    if (!input) return;
    const { w, s, b, g } = indices(input);
    const group = setGroupAt(current.weeks[w].sessions[s], b, g);
    const value = Number(input.value);
    if (!Number.isFinite(value)) return;
    group[input.dataset.edit] = value;
    edited = true;
    paint(out);
  });
}

function indices(el) {
  return {
    w: Number(el.dataset.w),
    s: Number(el.dataset.s),
    b: Number(el.dataset.b),
    g: Number(el.dataset.g)
  };
}

/**
 * Read stored state and restore the draft, if there is one.
 *
 * A missing draft is not an error and neither is an unreadable database: a fresh
 * install and an evicted one are indistinguishable here, and ADR-004 records
 * eviction as expected iOS Safari behaviour rather than a fault. A CORRUPT store
 * is different - state.js throws, and this reports it without overwriting
 * anything, because a silent overwrite of the one copy is unrecoverable.
 */
async function hydrate(out, form) {
  if (!db.available()) {
    storageNote = 'This browser has no storage available here, so drafts are not saved. Export to keep one.';
    paintStatus();
    return;
  }
  try {
    persisted = await db.load();
  } catch (err) {
    persisted = null;
    storageNote = `Stored data could not be read (${err.message}). It has been left untouched, not overwritten.`;
    paintStatus();
    // The editor needs no stored data to render, so it must not be gated behind
    // a successful load (#8). It was, and an unreadable store left the panel
    // silently empty -- a blank section reads as a broken build.
    paintProfiles();
    return;
  }
  restoreDraft(out, form);
  // AFTER the load, not only before it. paintProfiles() runs at mount while
  // `persisted` is still null, so it renders the shipped profiles alone; without
  // a repaint here an authored profile was written, read back correctly, and
  // still absent from the picker after every reload (#8).
  paintProfiles();
}

/** Put the stored draft back on screen and back into the form. */
function restoreDraft(out, form) {
  const draft = persisted?.plans.find((p) => p.id === DRAFT_ID);
  if (!draft) { paintStatus(); return; }

  hydrating = true;
  try {
    currentRequest = draft.request;
    current = draft.program;
    edited = draft.edited === true;
    // A named seed resolves to an integer, and only the integer is in the
    // request - so the label has to be stored beside it or "Mine" comes back as
    // 1276318216 after a reload.
    seedLabel = draft.seedLabel ?? '';
    visibleDay = 0;
    restoreForm(form, draft);
    paint(out);
  } finally {
    hydrating = false;
  }
  paintStatus();
}

/** Reflect a restored request back into the controls that produced it. */
/** Hold Sessions / week at or below the number of available days. */
function clampSessions(form) {
  const available = form.querySelectorAll('[name=availableDay]:checked').length;
  const input = form.daysPerWeek;
  input.max = String(Math.max(1, available));
  if (available > 0 && Number(input.value) > available) input.value = String(available);
}

function restoreForm(form, draft) {
  const r = draft.request;
  if (draft.scope) form.scope.value = draft.scope;
  scope = form.scope.value;
  form.styleId.value = r.styleId;
  form.daysPerWeek.value = r.daysPerWeek;
  // Restored explicitly. Without this a stored plan reloads with the default
  // availability, which reads as the app forgetting what the athlete picked.
  // Plans saved before availability existed have no field, so everything is
  // ticked - the widest honest assumption.
  const avail = r.availableDays ?? ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'];
  for (const box of form.querySelectorAll('[name=availableDay]')) {
    box.checked = avail.includes(box.value);
  }
  clampSessions(form);
  form.blockWeeks.value = r.blockWeeks;
  form.equipmentProfile.value = r.equipmentProfile;
  if (form.skillLevel) form.skillLevel.value = r.athlete?.skillLevel ?? 2;
  form.seed.value = seedLabel || String(r.seed);
  form.querySelector('.block-only').hidden = scope === 'session';
}

/** Collapse a burst of edits into one write. */
function scheduleSave() {
  if (hydrating || !current || !db.available()) return;
  clearTimeout(saveTimer);
  saveTimer = setTimeout(flushSave, 600);
}

/**
 * Write the draft now. Awaited by export, so the file is never one edit behind.
 *
 * `createdAt` is preserved across saves. Refreshing it every time would make the
 * record differ on every keystroke for no reason, and #35's gate compares stored
 * state.
 */
async function flushSave() {
  clearTimeout(saveTimer);
  saveTimer = null;
  if (hydrating || !current) return;

  const base = persisted ?? emptyState();
  const previous = base.plans.find((p) => p.id === DRAFT_ID);
  const next = putPlan(base, {
    id: DRAFT_ID,
    createdAt: previous?.createdAt ?? new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    edited,
    seedLabel,
    scope,
    request: currentRequest,
    program: current
  });

  const { ok, error } = await db.trySave(next);
  if (ok) {
    persisted = next;
    if (storageNote.startsWith('Not saved')) storageNote = '';
  } else {
    // Visible, never silent. There is no server to fall back on (ADR-004).
    storageNote = `Not saved: ${error?.message ?? 'storage unavailable'}. Export to keep this draft.`;
  }
  paintStatus();
}

/**
 * ADR-031 requires the last import date wherever progression-derived numbers
 * appear. There are none until M8, so it lives here - visible rather than
 * technically satisfied.
 */
/**
 * Group unmapped imported sets into one review row per source exercise (#57).
 *
 * Pure and exported so the queue can be asserted without a DOM. It previously
 * lived inside `if (csvBtn)` in paintStatus, where nothing could reach it.
 */
export function buildReviewQueue(importedSets = []) {
  const byId = new Map();
  for (const r of importedSets) {
    if (r.exerciseId !== null) continue;
    const key = r.sourceExerciseId ?? r.sourceExerciseName;
    const seen = byId.get(key);
    if (seen) { seen.sets += 1; continue; }
    byId.set(key, {
      fitnotesId: r.sourceExerciseId,
      sourceExerciseName: r.sourceExerciseName,
      tier: null,
      sets: 1
    });
  }
  return [...byId.values()].sort((a, b) => b.sets - a.sets);
}

/** Refresh the destination-date preview from the plan currently on screen. */
/**
 * The equipment editor (#8), and the merge that makes an authored profile usable.
 *
 * `currentDefs.equipment` is rebuilt from shipped + authored on every paint.
 * Without it validateRequest() refuses the profile as unknown the moment it is
 * selected -- defs.js is a static import and knows nothing about stored state.
 */
function paintProfiles() {
  const el = document.querySelector('#profile-editor');
  if (!el || !currentDefs) return;

  const authored = persisted?.equipmentProfiles ?? [];
  currentDefs = { ...currentDefs, equipment: mergeProfiles(shippedProfiles, authored) };

  const selected = document.querySelector('[name=equipmentProfile]')?.value;
  const editing = authored.find((p) => p.id === selected) ?? null;
  const owned = editing?.available
    ?? currentDefs.equipment.find((p) => p.id === selected)?.available
    ?? [];

  el.innerHTML = renderProfileEditor(tokenChoices(currentDefs.exercises, owned), {
    name: editing?.name ?? '',
    editingId: editing?.id ?? null,
    authored
  });

  // Keep the picker in step with what exists, preserving the selection.
  const picker = document.querySelector('[name=equipmentProfile]');
  if (picker) {
    const keep = picker.value;
    picker.innerHTML = currentDefs.equipment
      .map((p) => `<option value="${esc(p.id)}">${esc(p.name)}${p.userDefined ? ' (yours)' : ''}</option>`)
      .join('');
    if (currentDefs.equipment.some((p) => p.id === keep)) picker.value = keep;
  }
}

function paintDates() {
  const el = document.querySelector('#date-preview');
  const startEl = document.querySelector('#export-start');
  if (!el || !startEl) return;
  if (!current || !startEl.value) { el.innerHTML = ''; return; }
  try {
    const state = persisted ?? emptyState();
    // Notes are attached HERE rather than inside planDates(): that function is
    // pure and lives in storage/, and notes are a UI concern joined on the date
    // it already computed.
    const rows = planDates(current, startEl.value, state.importedSets, dateOverrides)
      .map((r) => {
        const n = notesForDate(state, r.date);
        return { ...r, importedNote: n.imported, authoredNote: n.authored };
      });
    el.innerHTML = renderDatePreview(rows);
  } catch (err) {
    // A plan with no schedule has no dates. Say which, rather than rendering
    // nothing and leaving an empty panel to be read as a bug.
    el.innerHTML = `<p class="note">${esc(err.message)}</p>`;
  }
}

function paintStatus() {
  // Live rows only. A superseded row is history, not the current answer, and
  // showing both would read as two conflicting maxes for one lift.
  if (maxListEl) {
    const live = (persisted?.exerciseMax ?? []).filter((r) => r.supersededAt == null);
    maxListEl.textContent = live.length
      ? live
          .slice()
          .sort((a, b) => (a.exerciseId < b.exerciseId ? -1 : 1))
          .map((r) => r.exerciseId + ' ' + r.e1rm + ' lb (' + r.source + ')')
          .join(' | ')
      : 'No maxes entered yet.';
  }

  const rows = persisted?.importedSets?.length ?? 0;

  // Rebuilt from stored rows on load, so the queue survives a reload rather
  // than existing only in the session that imported. NOT conditional on the
  // export button: this block used to sit inside `if (csvBtn)`, so a markup
  // change that dropped #export-csv would have silently stopped unmapped sets
  // being reviewable (#57). The review queue has nothing to do with CSV export.
  if (!importReview.length && rows) {
    importReview = buildReviewQueue(persisted.importedSets);
  }

  // Nothing to export until the FitNotes import lands (#24), so the button is
  // disabled rather than left clickable and immediately apologetic. A control
  // that cannot succeed in the current state reads as a defect.
  const csvBtn = document.querySelector('#export-csv');
  if (csvBtn) {
    csvBtn.disabled = rows === 0;
    csvBtn.title = rows === 0
      ? 'No imported history yet \u2014 available after a FitNotes import (#24)'
      : `Export ${rows} imported sets as CSV`;
  }

  paintReview();
  // Imported history changes which dates clash, so the preview follows it.
  paintDates();

  if (!statusEl) return;
  const last = persisted?.meta?.lastImportAt;
  const parts = [];
  if (storageNote) parts.push(storageNote);
  parts.push(last
    ? `Last FitNotes import: ${last.slice(0, 10)}.`
    : 'No FitNotes history imported yet.');
  statusEl.textContent = parts.join(' ');
}

/**
 * What the generator could not honour about the REQUEST — #51.
 *
 * Read straight off the program rather than held in module state: `storageNote`
 * is cleared on every successful save, which would take this with it, and a
 * second copy of the rule in the UI is how two copies drift apart. The engine
 * decided this; the UI only phrases it.
 *
 * Same honesty mechanism as the omission report in #43: name the real cause.
 * "You asked for 7 and got 6" without "no 7-session split template exists"
 * reads as a bug in the app rather than a limit of the catalog, and the athlete
 * cannot act on it.
 *
 * Deliberately not the word "reduced". Only one conditioning split exists, so a
 * 1-session HIIT request resolves UPWARD to 3 — being handed two sessions you
 * did not ask for is a recovery and time claim you never made, and it needs
 * saying just as much.
 */
export function sessionNoticeHtml(program) {
  const mm = program?.sessionMismatch;
  if (!mm) return '';
  const verb = mm.resolved > mm.requested ? 'has' : 'has only';
  return `<p class="request-note" role="status">You asked for ${mm.requested}
    ${mm.requested === 1 ? 'session' : 'sessions'} a week; this program ${verb}
    ${mm.resolved}, because ${esc(mm.reason)}. Available for this style:
    ${mm.available.join(', ')}.</p>`;
}

function paint(out) {
  if (!current) return;
  // ONE save anchor. Every mutation path - assignment, splice, swap, remove,
  // regenerate - mutates `current` and then calls paint(out), so hooking here
  // covers all of them. Four call sites would be four chances to miss one.
  scheduleSave();
  const style = currentDefs.styles.find((s) => s.id === current.styleId);
  const seedText = seedLabel || String(current.seed);
  const seedTitle = seedLabel
    ? `Named seed “${esc(seedLabel)}” resolves to ${current.seed}`
    : `Resolved seed ${current.seed}`;
  const editMessage = edited
    ? '<p class="edit-note">This draft has local edits, saved automatically. Regenerating replaces them.</p>'
    : '<p class="edit-note">Sets and reps are editable; draft edits remain only on this screen. Intensity is prescribed as a percentage of 1RM — absolute loads need logged maxes (M7).</p>';

  const head = `
    <div class="program-head">
      <h2>${esc(style.name)}</h2>
      <p class="meta">
        ${scope === 'session' ? `${(current.weeks[0]?.sessions.length ?? 0)} split days · session preview` : `${current.weeks.length} weeks × ${(current.weeks[0]?.sessions.length ?? 0)} days`}
        · seed <button class="ghost seed-copy" data-copy-seed="${esc(String(current.seed))}" title="${seedTitle}">${esc(seedText)}</button>
        ${seedLabel ? ` <span class="resolved-seed">(resolved: ${current.seed})</span>` : ''}
      </p>
      ${sessionNoticeHtml(current)}
      ${editMessage}
    </div>`;

  if (scope === 'session') {
    const sessions = current.weeks[0].sessions;
    visibleDay = Math.min(visibleDay, Math.max(0, sessions.length - 1));
    const tabs = `
      <nav class="day-picker" aria-label="Split day preview">
        ${sessions.map((s, i) => `
          <button class="ghost day-tab${i === visibleDay ? ' selected' : ''}"
                  data-day="${i}" aria-pressed="${i === visibleDay}">
            ${esc(s.label)}
          </button>`).join('')}
      </nav>`;
    const context = `<p class="note">Day ${visibleDay + 1} of a ${sessions.length}-day week. Switch to All weeks to see the whole block.</p>`;
    out.innerHTML = head + tabs + context + renderSession(sessions[visibleDay], 0, visibleDay, style);
    return;
  }

  out.innerHTML = head + current.weeks.map((week, w) => `
    <h2 class="week">Week ${week.week}</h2>
    ${week.sessions.map((session, s) => renderSession(session, w, s, style)).join('')}
  `).join('');
}

export function renderSession(session, w, s, style) {
  const groups = allSetGroups(session);
  const domainMeta = session.domain === 'load'
    ? `${session.fatigueUsed ?? groups.reduce((n, g) => n + (g.fatigueCost ?? 0), 0)} / ${session.fatigueBudget ?? style.fatigueBudget} fatigue`
    : sessionTiming(session);
  const timing = '';

  return `
    <article class="card session">
      <h3><span class="day-index">Day ${s + 1}</span>${esc(session.label)}</h3>
      ${session.blocks.length
        ? `<ul class="blocks">${session.blocks.map((block, b) => renderBlock(block, w, s, b, session.domain)).join('')}</ul>`
        : emptySession(session)}
      ${renderOmitted(session.omitted)}
      <p class="meta">${domainMeta}${timing ? ` · ${timing}` : ''}</p>
    </article>`;
}

function renderBlock(block, w, s, b, domain) {
  const type = block.blockType ?? 'straight';
  const heading = type === 'straight'
    ? ''
    : `<div class="block-group-head"><strong>${esc(blockLabel(type))}</strong><span class="tag">${block.setGroups.length} exercises</span></div>`;

  return `
    <li class="block block-${esc(type)}">
      ${heading}
      <ol class="setgroups">
        ${block.setGroups.map((group, g) => renderSetGroup(group, w, s, b, g, domain, type, block.rounds)).join('')}
      </ol>
    </li>`;
}

function renderSetGroup(group, w, s, b, g, domain, blockType, rounds) {
  const p = group;
  const role = group.role ? `<span class="tag">${esc(group.role)}</span>` : '';
  const warmup = group.warmupRequired
    ? '<span class="tag warn-tag" title="Perform appropriate warm-up sets before the prescribed work sets">warm-up required</span>'
    : '';
  const marker = blockType === 'straight' ? '' : `<span class="marker">${g + 1}</span>`;
  const swapped = group.swappedFrom
    ? `<p class="note">Swapped from ${esc(group.swappedFrom.name)}</p>`
    : '';

  const controls = domain === 'load'
    ? loadControls(p, w, s, b, g)
    : timeControls(p, w, s, b, g, rounds);

  return `
    <li class="setgroup${group.swappedFrom ? ' swapped' : ''}">
      <div class="block-head">
        ${marker}<strong>${esc(group.name)}</strong>${role}${warmup}
      </div>
      ${controls}
      ${swapped}
    </li>`;
}

function loadControls(p, w, s, b, g) {
  // No absolute load until logged maxes exist (M7). Percent-of-1RM is all the
  // engine can honestly prescribe, so there is no load branch to fall back to.
  const load = p.intensityOf1RM != null
      ? `${formatNumber(p.intensityOf1RM * 100)}% 1RM`
      : 'load not prescribed';
  const intensity = [load, p.rir != null ? `RIR ${formatNumber(p.rir)}` : '', p.restSeconds != null ? `${p.restSeconds}s rest` : '']
    .filter(Boolean).join(' · ');

  return `
    <div class="block-edit">
      ${numberEdit('sets', p.sets, w, s, b, g, 1)}
      ${numberEdit('reps', p.reps, w, s, b, g, 1)}
      <p class="intensity">${esc(intensity)}</p>
      ${editActions(w, s, b, g)}
    </div>`;
}

function timeControls(p, w, s, b, g, rounds) {
  const details = [
    p.workSeconds != null ? `${p.workSeconds}s work` : '',
    p.restSeconds != null ? `${p.restSeconds}s rest` : '',
    rounds != null ? `${rounds} rounds` : ''
  ].filter(Boolean).join(' · ');

  return `
    <div class="block-edit">
      ${p.workSeconds != null ? numberEdit('workSeconds', p.workSeconds, w, s, b, g, 1, 'work (sec)') : ''}
      ${p.restSeconds != null ? numberEdit('restSeconds', p.restSeconds, w, s, b, g, 1, 'rest (sec)') : ''}
      <p class="intensity">${esc(details || 'timed prescription')}</p>
      ${editActions(w, s, b, g)}
    </div>`;
}

function numberEdit(field, value, w, s, b, g, step = 1, label = field) {
  return `
    <label>${esc(label)}
      <input type="number" min="0" step="${step}" value="${value ?? ''}"
             data-edit="${field}" data-w="${w}" data-s="${s}" data-b="${b}" data-g="${g}" />
    </label>`;
}

function editActions(w, s, b, g) {
  const data = `data-w="${w}" data-s="${s}" data-b="${b}" data-g="${g}"`;
  return `
    <button class="action-button" data-swap ${data}>Swap</button>
    <button class="action-button danger" data-remove ${data}>Remove</button>`;
}

function toggleSwapList(out, button, w, s, b, g) {
  const existing = button.closest('.setgroup')?.querySelector('.swap-list');
  if (existing) { existing.remove(); return; }

  const group = setGroupAt(current.weeks[w].sessions[s], b, g);
  const alternatives = rankSubstitutes(group.exerciseId, currentDefs, currentRequest, 5);
  const list = document.createElement('ul');
  list.className = 'swap-list';
  list.innerHTML = alternatives.length
    ? alternatives.map((x) => `
        <li>
          <button class="ghost" data-pick="${esc(x.exercise.id)}"
                  data-w="${w}" data-s="${s}" data-b="${b}" data-g="${g}">
            ${esc(x.exercise.name)}
          </button>
          <span class="meta">${formatNumber(x.score)}</span>
        </li>`).join('')
    : '<li class="note">No compatible substitutes found.</li>';
  button.closest('.setgroup')?.append(list);
}

function replaceSetGroup(w, s, b, g, replacementId) {
  const group = setGroupAt(current.weeks[w].sessions[s], b, g);
  const replacement = currentDefs.exercises.find((x) => x.id === replacementId);
  if (!replacement) return;
  const original = group.swappedFrom ?? { id: group.exerciseId, name: group.name };
  group.exerciseId = replacement.id;
  group.name = replacement.name;
  group.fatigueCost = replacement.fatigueCost;
  group.warmupRequired = replacement.warmupRequired;
  group.swappedFrom = original;
}

/**
 * The dates a plan will export to, before it exports — #54.
 *
 * #25 required that dates be reviewable before export. What shipped told the
 * athlete afterwards: a confirm listing clashes, and a status line naming the
 * range once the file was already downloaded. Neither is a preview.
 *
 * Collisions are marked in the list itself rather than only in a modal. The
 * confirm was removed with this — the same fact stated twice, once readably and
 * once blockingly, is not two safeguards.
 */
/**
 * What a moved date means for the work already written — #54.
 *
 * The first version of this said "Written for a compressed gap; this date gives
 * 2 days. Volume was not recalculated." That is engine vocabulary ("compressed"
 * is a gapClass value) and it says nothing the athlete can act on. It also read
 * as a warning in BOTH directions, when only one of them is a caution.
 *
 * The engine reduces accessory volume by compressedAccessoryMultiplier when a
 * session follows the day before, so:
 *   built compressed, now rested  -> less work than the new spacing allows
 *   built rested, now back-to-back -> more work than the new spacing supports
 * Only the second is a risk, and each names the fix rather than the mechanism.
 */
function gapNote(r) {
  const days = `${r.spacing} day${r.spacing === 1 ? '' : 's'}`;
  return r.gap === 'compressed'
    ? `Written as a lighter session because it followed the day before. It now has `
      + `${days} of rest, so it has less work than this spacing allows. Regenerate `
      + `for full volume.`
    : `Written for a full rest day before it. It now follows the previous session `
      + `after ${days}, so it may be more work than you can recover from.`;
}

/**
 * Every token the editor can offer (#8).
 *
 * The catalog's vocabulary UNION whatever the profile already owns. Deriving it
 * from the catalog alone would silently drop a token the athlete owns but no
 * exercise uses yet -- `rings` on home-garage is exactly that, and pruning it on
 * first save is the kind of quiet data loss this repo keeps finding. An unused
 * token is marked, never hidden.
 */
export function tokenChoices(catalog, owned = []) {
  const used = new Map();
  for (const ex of catalog) for (const t of ex.equipment ?? []) used.set(t, (used.get(t) ?? 0) + 1);
  const all = new Set([...used.keys(), ...owned]);
  return [...all].sort().map((token) => ({
    token,
    uses: used.get(token) ?? 0,
    owned: owned.includes(token)
  }));
}

/** Shipped profiles first, then authored ones. Authored may not shadow (state.js). */
export function mergeProfiles(shipped, authored = []) {
  const ids = new Set(shipped.map((p) => p.id));
  return [...shipped, ...authored.filter((p) => !ids.has(p.id))];
}

/** A stable id from a display name. Collisions are resolved by the caller. */
export function profileId(name) {
  return String(name).toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

export function renderProfileEditor(choices, { name = '', editingId = null, authored = [] } = {}) {
  const owned = choices.filter((c) => c.owned).length;
  return `
    <label>Profile name
      <input type="text" id="profile-name" value="${esc(name)}" placeholder="My Gym" />
    </label>
    <p class="note">${owned} of ${choices.length} selected. Presence, not quantity (ADR-014):
    tick what you have access to, not how much of it.</p>
    <ul class="token-list">
      ${choices.map((c) => `
        <li>
          <label title="${c.uses === 0 ? 'No exercise uses this token yet' : `${c.uses} exercises`}">
            <input type="checkbox" name="token" value="${esc(c.token)}" ${c.owned ? 'checked' : ''} />
            <span>${esc(c.token.replace(/_/g, ' '))}</span>
            ${c.uses === 0 ? '<span class="tag">unused</span>' : ''}
          </label>
        </li>`).join('')}
    </ul>
    <div class="storage-actions">
      <button type="button" id="profile-save" class="ghost">${editingId ? 'Update' : 'Save'} profile</button>
      ${editingId ? `<button type="button" id="profile-delete" class="ghost">Delete</button>` : ''}
    </div>
    ${authored.length ? `<p class="note">Your profiles: ${authored.map((p) => esc(p.name)).join(', ')}</p>` : ''}`;
}

/**
 * Day-level notes against a date (#50).
 *
 * Imported and authored are rendered SEPARATELY and labelled. They are not the
 * same kind of fact: an imported note is what FitNotes recorded on that day, an
 * authored one is an instruction for a session that has not happened. Merging
 * them into one box would make an import look like it had overwritten your
 * writing even though it cannot.
 *
 * Nothing parses the text (ADR-002). It is escaped and displayed, never read.
 */
function dayNoteHtml(r) {
  const imported = r.importedNote
    ? `<span class="note day-note imported" title="From your FitNotes history">${esc(r.importedNote)}</span>`
    : '';
  const authored = `<input type="text" class="day-note-input" data-note-date="${esc(r.date)}"
       value="${esc(r.authoredNote ?? '')}" placeholder="Add a note for this session"
       aria-label="Note for ${esc(r.label)} on ${esc(r.date)}" />`;
  return imported + authored;
}

export function renderDatePreview(rows) {
  if (!rows?.length) return '';
  const clashes = rows.filter((r) => r.collides).length;
  return `
    <section class="date-list" aria-label="Destination dates">
      <h4>${rows.length} ${rows.length === 1 ? 'session' : 'sessions'}, ${esc(rows[0].date)} to ${esc(rows[rows.length - 1].date)}</h4>
      ${clashes ? `<p class="note warn">${clashes} ${clashes === 1 ? 'date already holds' : 'dates already hold'} imported history. Exporting ADDS rows rather than replacing them, so those days will hold both.</p>` : ''}
      <ol class="dates">
        ${rows.map((r) => `
          <li class="${[r.collides && 'collides', r.moved && 'moved', r.outOfOrder && 'out-of-order'].filter(Boolean).join(' ')}">
            <input type="date" class="date-input" value="${esc(r.date)}"
                   data-date-index="${r.index}" aria-label="Date for ${esc(r.label)}" />
            <span class="label">${esc(r.label)}</span>
            ${r.collides ? '<span class="tag warn-tag" title="This date already holds imported history">history exists</span>' : ''}
            ${r.outOfOrder ? '<span class="tag warn-tag">on or before the previous session</span>' : ''}
            ${r.gapChanged ? `<span class="note gap-note">${gapNote(r)}</span>` : ''}
            ${dayNoteHtml(r)}
          </li>`).join('')}
      </ol>
      ${rows.some((r) => r.moved) ? '<p class="note">Moved dates apply to this export only.</p>' : ''}
    </section>`;
}

export function renderOmitted(omitted = []) {
  if (!omitted.length) return '';
  return `
    <section class="omitted" aria-label="Omitted training patterns">
      <h4>Not included</h4>
      <ul>
        ${omitted.map((x) => x.pattern == null
          ? `<li><strong>This session</strong> \u2014 ${esc(omitReason(x))}</li>`
          : `<li><strong>${esc(patternLabel(x.pattern))}</strong> \u2014 ${esc(omitReason(x))}</li>`
        ).join('')}
      </ul>
    </section>`;
}

function coverageHtml(err, defs, request) {
  const profile = defs.equipment.find((p) => p.id === request.equipmentProfile);
  const gaps = err.gaps ?? [];
  return `
    <article class="card error-card">
      <h2>Equipment coverage problem</h2>
      <p>The ${esc(profile?.name ?? request.equipmentProfile)} profile cannot perform every required pattern.</p>
      <ul class="gap-list">
        ${gaps.map((gap) => `
          <li>
            <strong>${esc(gap.pattern)}</strong>
            ${gap.suggestions?.length
              ? `<span class="fix">Add ${gap.suggestions.map((s) => esc(s.join(' + '))).join(' or ')}</span>`
              : '<span class="fix">No compatible catalog option is available.</span>'}
          </li>`).join('')}
      </ul>
    </article>`;
}

function genericErrorHtml(err) {
  return `
    <article class="card error-card">
      <h2>Could not generate the plan</h2>
      <p>${esc(err?.message ?? 'Unknown error')}</p>
    </article>`;
}

export function blockLabel(type) {
  return ({ superset: 'Superset', circuit: 'Circuit', amrap: 'AMRAP' })[type] ?? type;
}

function formatNumber(value) {
  return Number.isInteger(Number(value)) ? String(Number(value)) : Number(value).toFixed(1);
}

export function esc(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}


/** Rounds and the time cap sit on the block (ADR-027), never on the session. */
export function sessionTiming(session) {
  const rounds = session.blocks.reduce((n, b) => Math.max(n, b.rounds ?? 0), 0);
  const cap = session.blocks.reduce((n, b) => Math.max(n, b.timeCapSeconds ?? 0), 0);
  return [
    rounds ? `${rounds} rounds` : '',
    cap ? `${Math.round(cap / 60)} min cap` : '',
  ].filter(Boolean).join(' · ') || 'timed session';
}

/**
 * A session with no blocks is not an error — the engine reports the gap in
 * omitted[] and carries on (539f900). But it must say so, or it reads as broken.
 */
export function emptySession(session) {
  // Was keyed on pattern === 'monostructural' and promised the rower/bike/jump
  // rope catalog "ships in M6". It shipped in #28, so the banner told the user
  // to wait for something already installed (#43). Every reason code is
  // translated in omitReason(); the banner defers to it rather than keeping a
  // second, staler opinion.
  const why = (session.omitted ?? [])
    .map((x) => omitReason(x))
    .filter((v, i, all) => all.indexOf(v) === i);

  return `<p class="edit-note">Nothing could be prescribed for this session. ${
    why.length
      ? esc(why.join('; ')) + '.'
      : 'No exercise in the catalog matches this session\u2019s patterns under the current equipment profile.'
  }</p>`;
}

/**
 * Exercises the import could not map, listed until they are resolved.
 *
 * The wording states the consequence rather than the fact, because the fact is
 * not self-explanatory: these sets ARE stored, and they are invisible to
 * progression, because ADR-023 keys e1RM on `exerciseId` and these rows have
 * none. An athlete reading "17 sets unmatched" would reasonably assume the sets
 * were lost; the opposite is true and the effect is subtler.
 *
 * Resolution happens in data/fitnotes/fitnotes-mapping.csv, not here. ADR-031
 * replaces imported history on every import, so a mapping recorded against a
 * stored row would be destroyed by the next one (#26).
 */
function paintReview() {
  if (!reviewEl) return;
  if (!importReview.length) { reviewEl.innerHTML = ''; return; }

  const total = importReview.reduce((n, r) => n + r.sets, 0);
  reviewEl.innerHTML = `
    <section class="review-queue" aria-label="Unmatched imported exercises">
      <h4>${importReview.length} unmatched ${importReview.length === 1 ? 'exercise' : 'exercises'}</h4>
      <p class="note">${total} imported ${total === 1 ? 'set is' : 'sets are'} kept but excluded from
      progression until mapped in <code>data/fitnotes/fitnotes-mapping.csv</code>.</p>
      <ul>
        ${importReview.map((r) => `
          <li><strong>${esc(r.sourceExerciseName ?? 'unnamed')}</strong>
          ${DASH_HTML} ${r.sets} ${r.sets === 1 ? 'set' : 'sets'}
          ${r.tier ? `<span class="tag">${esc(r.tier)}</span>` : ''}</li>`).join('')}
      </ul>
    </section>`;
}

const DASH_HTML = '\u2014';

export function patternLabel(p) {
  const NAMES = {
    monostructural: 'Steady-state conditioning',
    push_h: 'Horizontal push', push_v: 'Vertical push',
    pull_h: 'Horizontal pull', pull_v: 'Vertical pull',
  };
  // Null is legitimate: a `count-not-reachable` omission is about the session's
  // total, not about any one pattern, so it has no pattern to name. This used to
  // throw on `p.replace` and refuse the WHOLE plan -- reachable from bodybuilding
  // at 5, 6 or 7 sessions (#51).
  if (p == null) return '';
  return NAMES[p] ?? p.replace(/_/g, ' ').replace(/^./, (c) => c.toUpperCase());
}

/** Engine reason codes are vocabulary, not prose. Translate at the boundary. */
export function omitReason(x) {
  // Keyed on the REASON, never on the pattern. The old first line returned
  // 'deferred to M6' for any monostructural omission, which stopped being
  // true when 13_conditioning.csv landed 14 rows (#28) and pre-empted every
  // other cause besides (#43).
  switch (x.reason) {
    // The style does not train this pattern. Not a gap - a choice.
    case 'style-emphasis-zero':
      return 'not trained by this style';
    case 'no-unused-candidates':
      return 'no eligible exercise left for this pattern';
    case 'no-catalog-rows':
      return 'no exercise in the catalog for this pattern';
    case 'equipment':
      return 'no exercise your equipment profile can supply';
    case 'fatigue-budget-exhausted':
      return 'the session fatigue budget was already spent';
    case 'no-time-domain':
      return 'no exercise here can be prescribed for time';
    case 'reps-for-time-window-too-long':
      return 'the work window is too long to prescribe as continuous reps';
    case 'session-under-filled':
      return `only ${x.placed} of ${x.target} exercises could be placed`;
    case 'count-not-reachable':
      // Numbers, not a vague shortfall (#43). `requested` is what the style
      // asks for, `placed` what the catalog and fatigue budget allowed.
      return x.placed != null && x.requested != null
        ? `only ${x.placed} of ${x.requested} exercises could be placed`
        : 'the session could not reach its exercise count';
    default:
      return x.reason ?? 'no eligible exercise';
  }
}
